spring.application.name=note-application
# JPA configuracion de la base de datos en este caso H2
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
# Configuracion para el actuator
#management.endpoints.web.exposure.include=health,info,metrics,env
#management.endpoint.health.show-details=always